# Generated by Django 4.2.6 on 2023-11-02 03:33

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "to do": "An issue that has not yet been started",
        "in progress": "An issue that is being worked on",
        "done": "An issue for which work has been completed",
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
